// Auto-generated by vite-plugin-modal-types
import type { ReturnType as ReturnType_DemoForm, Props as Props_DemoForm } from '../../modals/DemoForm.mdl';

export interface ModalRegistry {
  /** 
   * @source src/modals/DemoBasic.mdl.tsx
   * @see {@link file:///home/edi/Documents/MYPROJECTS/react_modal/examples/demo-site/src/modals/DemoBasic.mdl.tsx}
   */
  'DemoBasic': {
    ReturnType: any;
    Props: any;
  };
  /** 
   * @source src/modals/DemoForm.mdl.tsx
   * @see {@link file:///home/edi/Documents/MYPROJECTS/react_modal/examples/demo-site/src/modals/DemoForm.mdl.tsx}
   */
  'DemoForm': {
    ReturnType: ReturnType_DemoForm;
    Props: Props_DemoForm;
  };
  /** 
   * @source src/modals/DemoLazy.amdl.tsx
   * @see {@link file:///home/edi/Documents/MYPROJECTS/react_modal/examples/demo-site/src/modals/DemoLazy.amdl.tsx}
   */
  'DemoLazy': {
    ReturnType: any;
    Props: any;
  };
  /** 
   * @source src/modals/DemoStacked.mdl.tsx
   * @see {@link file:///home/edi/Documents/MYPROJECTS/react_modal/examples/demo-site/src/modals/DemoStacked.mdl.tsx}
   */
  'DemoStacked': {
    ReturnType: any;
    Props: any;
  };
}

  /** 
   * @source src/modals/DemoBasic.mdl.tsx
   * @see {@link file:///home/edi/Documents/MYPROJECTS/react_modal/examples/demo-site/src/modals/DemoBasic.mdl.tsx}
   */
export type DemoBasic = 'DemoBasic';

  /** 
   * @source src/modals/DemoForm.mdl.tsx
   * @see {@link file:///home/edi/Documents/MYPROJECTS/react_modal/examples/demo-site/src/modals/DemoForm.mdl.tsx}
   */
export type DemoForm = 'DemoForm';

  /** 
   * @source src/modals/DemoLazy.amdl.tsx
   * @see {@link file:///home/edi/Documents/MYPROJECTS/react_modal/examples/demo-site/src/modals/DemoLazy.amdl.tsx}
   */
export type DemoLazy = 'DemoLazy';

  /** 
   * @source src/modals/DemoStacked.mdl.tsx
   * @see {@link file:///home/edi/Documents/MYPROJECTS/react_modal/examples/demo-site/src/modals/DemoStacked.mdl.tsx}
   */
export type DemoStacked = 'DemoStacked';

/**
 * Constant object for all modal names.
 * Use this for better "Go to Definition" support: openModal(MODALS.ConfirmationModal)
 */
export const MODALS = {
  /** 
   * @source src/modals/DemoBasic.mdl.tsx
   * @see {@link file:///home/edi/Documents/MYPROJECTS/react_modal/examples/demo-site/src/modals/DemoBasic.mdl.tsx}
   */
  DemoBasic: 'DemoBasic' as DemoBasic,
  /** 
   * @source src/modals/DemoForm.mdl.tsx
   * @see {@link file:///home/edi/Documents/MYPROJECTS/react_modal/examples/demo-site/src/modals/DemoForm.mdl.tsx}
   */
  DemoForm: 'DemoForm' as DemoForm,
  /** 
   * @source src/modals/DemoLazy.amdl.tsx
   * @see {@link file:///home/edi/Documents/MYPROJECTS/react_modal/examples/demo-site/src/modals/DemoLazy.amdl.tsx}
   */
  DemoLazy: 'DemoLazy' as DemoLazy,
  /** 
   * @source src/modals/DemoStacked.mdl.tsx
   * @see {@link file:///home/edi/Documents/MYPROJECTS/react_modal/examples/demo-site/src/modals/DemoStacked.mdl.tsx}
   */
  DemoStacked: 'DemoStacked' as DemoStacked,
} as const;

export type FileNames = DemoBasic | DemoForm | DemoLazy | DemoStacked;
