// Auto-generated by vite-plugin-modal-types


export interface ModalRegistry {

}

export interface ModalPropsRegistry {

}



/**
 * Constant object for all modal names.
 * Use this for better "Go to Definition" support: openModal(MODALS.ConfirmationModal)
 */
export const MODALS = {

} as const;

export type FileNames = never;
