// Auto-generated by vite-plugin-modal-types
import type { ReturnType as ReturnType_ConfirmationModal, Props as Props_ConfirmationModal } from '../../modals/ConfirmationModal.mdl';
import type { ReturnType as ReturnType_SelectTruckModal, Props as Props_SelectTruckModal } from '../../modals/SelectTruckModal.mdl';
import type { ReturnType as ReturnType_SortByModal, Props as Props_SortByModal } from '../../modals/SortByModal.mdl';
import type { ReturnType as ReturnType_Test } from '../../modals/Test.mdl';
import type { ReturnType as ReturnType_VehicleRegistrationModal } from '../../modals/VehicleRegistrationModal.mdl';
import type { Props as Props_BidDetail } from '../../routes/carrier/components/BidDetail.amdl';
import type { ReturnType as ReturnType_PlaceBid, Props as Props_PlaceBid } from '../../routes/carrier/components/PlaceBid.amdl';
import type { ReturnType as ReturnType_FilterSortModal, Props as Props_FilterSortModal } from '../../routes/shipper/(search-truck)/-components/FilterSortModal.mdl';
import type { Props as Props_AcceptedBIdMessage } from '../../routes/shipper/(shipper)/-components/AcceptedBIdMessage.mdl';
import type { Props as Props_CounterBidOffer } from '../../routes/shipper/(shipper)/-components/CounterBidOffer.amdl';
import type { ReturnType as ReturnType_ExtendPickupDate } from '../../routes/shipper/(shipper)/-components/ExtendPickupDate.amdl';
import type { Props as Props_RejectBid } from '../../routes/shipper/(shipper)/-components/RejectBid.amdl';
import type { Props as Props_ShipmentFilter } from '../../routes/shipper/-components/ShipmentFilter.amdl';
import type { ReturnType as ReturnType_BookableLoadsModal, Props as Props_BookableLoadsModal } from '../../routes-shared/my-modals/BookableLoadsModal.amdl';
import type { ReturnType as ReturnType_CarrierModal, Props as Props_CarrierModal } from '../../routes-shared/my-modals/CarrierModal.amdl';
import type { ReturnType as ReturnType_CompanyFilterModal, Props as Props_CompanyFilterModal } from '../../routes-shared/my-modals/CompanyFilterModal.amdl';
import type { ReturnType as ReturnType_LoadRequirementsModal, Props as Props_LoadRequirementsModal } from '../../routes-shared/my-modals/LoadRequirementsModal.amdl';
import type { ReturnType as ReturnType_PrivateLoadsModal, Props as Props_PrivateLoadsModal } from '../../routes-shared/my-modals/PrivateLoadsModal.amdl';
import type { ReturnType as ReturnType_SearchBackModal, Props as Props_SearchBackModal } from '../../routes-shared/my-modals/SearchBackModal.amdl';
import type { ReturnType as ReturnType_TruckDetailModal, Props as Props_TruckDetailModal } from '../../routes-shared/my-modals/TruckDetailModal.amdl';

export interface ModalRegistry {
  /** 
   * @source src/components/RegsiterForPushNotification.mdl.tsx
   * @see {@link file:///home/edi/Documents/workbeanch/new_work/raaz/src/components/RegsiterForPushNotification.mdl.tsx}
   */
  'RegsiterForPushNotification': {
    ReturnType: any;
    Props: any;
  };
  /** 
   * @source src/modals/ConfirmationModal.mdl.tsx
   * @see {@link file:///home/edi/Documents/workbeanch/new_work/raaz/src/modals/ConfirmationModal.mdl.tsx}
   */
  'ConfirmationModal': {
    ReturnType: ReturnType_ConfirmationModal;
    Props: Props_ConfirmationModal;
  };
  /** 
   * @source src/modals/SelectTruckModal.mdl.tsx
   * @see {@link file:///home/edi/Documents/workbeanch/new_work/raaz/src/modals/SelectTruckModal.mdl.tsx}
   */
  'SelectTruckModal': {
    ReturnType: ReturnType_SelectTruckModal;
    Props: Props_SelectTruckModal;
  };
  /** 
   * @source src/modals/SortByModal.mdl.tsx
   * @see {@link file:///home/edi/Documents/workbeanch/new_work/raaz/src/modals/SortByModal.mdl.tsx}
   */
  'SortByModal': {
    ReturnType: ReturnType_SortByModal;
    Props: Props_SortByModal;
  };
  /** 
   * @source src/modals/Test.mdl.tsx
   * @see {@link file:///home/edi/Documents/workbeanch/new_work/raaz/src/modals/Test.mdl.tsx}
   */
  'Test': {
    ReturnType: ReturnType_Test;
    Props: any;
  };
  /** 
   * @source src/modals/VehicleRegistrationModal.mdl.tsx
   * @see {@link file:///home/edi/Documents/workbeanch/new_work/raaz/src/modals/VehicleRegistrationModal.mdl.tsx}
   */
  'VehicleRegistrationModal': {
    ReturnType: ReturnType_VehicleRegistrationModal;
    Props: any;
  };
  /** 
   * @source src/routes/carrier/components/BidDetail.amdl.tsx
   * @see {@link file:///home/edi/Documents/workbeanch/new_work/raaz/src/routes/carrier/components/BidDetail.amdl.tsx}
   */
  'BidDetail': {
    ReturnType: any;
    Props: Props_BidDetail;
  };
  /** 
   * @source src/routes/carrier/components/PlaceBid.amdl.tsx
   * @see {@link file:///home/edi/Documents/workbeanch/new_work/raaz/src/routes/carrier/components/PlaceBid.amdl.tsx}
   */
  'PlaceBid': {
    ReturnType: ReturnType_PlaceBid;
    Props: Props_PlaceBid;
  };
  /** 
   * @source src/routes/shipper/(my-contact)/-components/AddCarrier.amdl.tsx
   * @see {@link file:///home/edi/Documents/workbeanch/new_work/raaz/src/routes/shipper/(my-contact)/-components/AddCarrier.amdl.tsx}
   */
  'AddCarrier': {
    ReturnType: any;
    Props: any;
  };
  /** 
   * @source src/routes/shipper/(my-contact)/-components/AddGroup.amdl.tsx
   * @see {@link file:///home/edi/Documents/workbeanch/new_work/raaz/src/routes/shipper/(my-contact)/-components/AddGroup.amdl.tsx}
   */
  'AddGroup': {
    ReturnType: any;
    Props: any;
  };
  /** 
   * @source src/routes/shipper/(my-contact)/-components/EditCarrier.amdl.tsx
   * @see {@link file:///home/edi/Documents/workbeanch/new_work/raaz/src/routes/shipper/(my-contact)/-components/EditCarrier.amdl.tsx}
   */
  'EditCarrier': {
    ReturnType: any;
    Props: any;
  };
  /** 
   * @source src/routes/shipper/(my-contact)/-components/EditGroup.amdl.tsx
   * @see {@link file:///home/edi/Documents/workbeanch/new_work/raaz/src/routes/shipper/(my-contact)/-components/EditGroup.amdl.tsx}
   */
  'EditGroup': {
    ReturnType: any;
    Props: any;
  };
  /** 
   * @source src/routes/shipper/(my-contact)/-components/UploadContactExcell.amdl.tsx
   * @see {@link file:///home/edi/Documents/workbeanch/new_work/raaz/src/routes/shipper/(my-contact)/-components/UploadContactExcell.amdl.tsx}
   */
  'UploadContactExcell': {
    ReturnType: any;
    Props: any;
  };
  /** 
   * @source src/routes/shipper/(search-truck)/-components/FilterSortModal.mdl.tsx
   * @see {@link file:///home/edi/Documents/workbeanch/new_work/raaz/src/routes/shipper/(search-truck)/-components/FilterSortModal.mdl.tsx}
   */
  'FilterSortModal': {
    ReturnType: ReturnType_FilterSortModal;
    Props: Props_FilterSortModal;
  };
  /** 
   * @source src/routes/shipper/(shipper)/-components/AcceptedBIdMessage.mdl.tsx
   * @see {@link file:///home/edi/Documents/workbeanch/new_work/raaz/src/routes/shipper/(shipper)/-components/AcceptedBIdMessage.mdl.tsx}
   */
  'AcceptedBIdMessage': {
    ReturnType: any;
    Props: Props_AcceptedBIdMessage;
  };
  /** 
   * @source src/routes/shipper/(shipper)/-components/CounterBidOffer.amdl.tsx
   * @see {@link file:///home/edi/Documents/workbeanch/new_work/raaz/src/routes/shipper/(shipper)/-components/CounterBidOffer.amdl.tsx}
   */
  'CounterBidOffer': {
    ReturnType: any;
    Props: Props_CounterBidOffer;
  };
  /** 
   * @source src/routes/shipper/(shipper)/-components/ExtendPickupDate.amdl.tsx
   * @see {@link file:///home/edi/Documents/workbeanch/new_work/raaz/src/routes/shipper/(shipper)/-components/ExtendPickupDate.amdl.tsx}
   */
  'ExtendPickupDate': {
    ReturnType: ReturnType_ExtendPickupDate;
    Props: any;
  };
  /** 
   * @source src/routes/shipper/(shipper)/-components/RejectBid.amdl.tsx
   * @see {@link file:///home/edi/Documents/workbeanch/new_work/raaz/src/routes/shipper/(shipper)/-components/RejectBid.amdl.tsx}
   */
  'RejectBid': {
    ReturnType: any;
    Props: Props_RejectBid;
  };
  /** 
   * @source src/routes/shipper/-components/ShipmentFilter.amdl.tsx
   * @see {@link file:///home/edi/Documents/workbeanch/new_work/raaz/src/routes/shipper/-components/ShipmentFilter.amdl.tsx}
   */
  'ShipmentFilter': {
    ReturnType: any;
    Props: Props_ShipmentFilter;
  };
  /** 
   * @source src/routes-shared/my-modals/BookableLoadsModal.amdl.tsx
   * @see {@link file:///home/edi/Documents/workbeanch/new_work/raaz/src/routes-shared/my-modals/BookableLoadsModal.amdl.tsx}
   */
  'BookableLoadsModal': {
    ReturnType: ReturnType_BookableLoadsModal;
    Props: Props_BookableLoadsModal;
  };
  /** 
   * @source src/routes-shared/my-modals/CarrierModal.amdl.tsx
   * @see {@link file:///home/edi/Documents/workbeanch/new_work/raaz/src/routes-shared/my-modals/CarrierModal.amdl.tsx}
   */
  'CarrierModal': {
    ReturnType: ReturnType_CarrierModal;
    Props: Props_CarrierModal;
  };
  /** 
   * @source src/routes-shared/my-modals/CompanyFilterModal.amdl.tsx
   * @see {@link file:///home/edi/Documents/workbeanch/new_work/raaz/src/routes-shared/my-modals/CompanyFilterModal.amdl.tsx}
   */
  'CompanyFilterModal': {
    ReturnType: ReturnType_CompanyFilterModal;
    Props: Props_CompanyFilterModal;
  };
  /** 
   * @source src/routes-shared/my-modals/LoadRequirementsModal.amdl.tsx
   * @see {@link file:///home/edi/Documents/workbeanch/new_work/raaz/src/routes-shared/my-modals/LoadRequirementsModal.amdl.tsx}
   */
  'LoadRequirementsModal': {
    ReturnType: ReturnType_LoadRequirementsModal;
    Props: Props_LoadRequirementsModal;
  };
  /** 
   * @source src/routes-shared/my-modals/PrivateLoadsModal.amdl.tsx
   * @see {@link file:///home/edi/Documents/workbeanch/new_work/raaz/src/routes-shared/my-modals/PrivateLoadsModal.amdl.tsx}
   */
  'PrivateLoadsModal': {
    ReturnType: ReturnType_PrivateLoadsModal;
    Props: Props_PrivateLoadsModal;
  };
  /** 
   * @source src/routes-shared/my-modals/SearchBackModal.amdl.tsx
   * @see {@link file:///home/edi/Documents/workbeanch/new_work/raaz/src/routes-shared/my-modals/SearchBackModal.amdl.tsx}
   */
  'SearchBackModal': {
    ReturnType: ReturnType_SearchBackModal;
    Props: Props_SearchBackModal;
  };
  /** 
   * @source src/routes-shared/my-modals/TruckDetailModal.amdl.tsx
   * @see {@link file:///home/edi/Documents/workbeanch/new_work/raaz/src/routes-shared/my-modals/TruckDetailModal.amdl.tsx}
   */
  'TruckDetailModal': {
    ReturnType: ReturnType_TruckDetailModal;
    Props: Props_TruckDetailModal;
  };
}

  /** 
   * @source src/components/RegsiterForPushNotification.mdl.tsx
   * @see {@link file:///home/edi/Documents/workbeanch/new_work/raaz/src/components/RegsiterForPushNotification.mdl.tsx}
   */
export type RegsiterForPushNotification = 'RegsiterForPushNotification';

  /** 
   * @source src/modals/ConfirmationModal.mdl.tsx
   * @see {@link file:///home/edi/Documents/workbeanch/new_work/raaz/src/modals/ConfirmationModal.mdl.tsx}
   */
export type ConfirmationModal = 'ConfirmationModal';

  /** 
   * @source src/modals/SelectTruckModal.mdl.tsx
   * @see {@link file:///home/edi/Documents/workbeanch/new_work/raaz/src/modals/SelectTruckModal.mdl.tsx}
   */
export type SelectTruckModal = 'SelectTruckModal';

  /** 
   * @source src/modals/SortByModal.mdl.tsx
   * @see {@link file:///home/edi/Documents/workbeanch/new_work/raaz/src/modals/SortByModal.mdl.tsx}
   */
export type SortByModal = 'SortByModal';

  /** 
   * @source src/modals/Test.mdl.tsx
   * @see {@link file:///home/edi/Documents/workbeanch/new_work/raaz/src/modals/Test.mdl.tsx}
   */
export type Test = 'Test';

  /** 
   * @source src/modals/VehicleRegistrationModal.mdl.tsx
   * @see {@link file:///home/edi/Documents/workbeanch/new_work/raaz/src/modals/VehicleRegistrationModal.mdl.tsx}
   */
export type VehicleRegistrationModal = 'VehicleRegistrationModal';

  /** 
   * @source src/routes/carrier/components/BidDetail.amdl.tsx
   * @see {@link file:///home/edi/Documents/workbeanch/new_work/raaz/src/routes/carrier/components/BidDetail.amdl.tsx}
   */
export type BidDetail = 'BidDetail';

  /** 
   * @source src/routes/carrier/components/PlaceBid.amdl.tsx
   * @see {@link file:///home/edi/Documents/workbeanch/new_work/raaz/src/routes/carrier/components/PlaceBid.amdl.tsx}
   */
export type PlaceBid = 'PlaceBid';

  /** 
   * @source src/routes/shipper/(my-contact)/-components/AddCarrier.amdl.tsx
   * @see {@link file:///home/edi/Documents/workbeanch/new_work/raaz/src/routes/shipper/(my-contact)/-components/AddCarrier.amdl.tsx}
   */
export type AddCarrier = 'AddCarrier';

  /** 
   * @source src/routes/shipper/(my-contact)/-components/AddGroup.amdl.tsx
   * @see {@link file:///home/edi/Documents/workbeanch/new_work/raaz/src/routes/shipper/(my-contact)/-components/AddGroup.amdl.tsx}
   */
export type AddGroup = 'AddGroup';

  /** 
   * @source src/routes/shipper/(my-contact)/-components/EditCarrier.amdl.tsx
   * @see {@link file:///home/edi/Documents/workbeanch/new_work/raaz/src/routes/shipper/(my-contact)/-components/EditCarrier.amdl.tsx}
   */
export type EditCarrier = 'EditCarrier';

  /** 
   * @source src/routes/shipper/(my-contact)/-components/EditGroup.amdl.tsx
   * @see {@link file:///home/edi/Documents/workbeanch/new_work/raaz/src/routes/shipper/(my-contact)/-components/EditGroup.amdl.tsx}
   */
export type EditGroup = 'EditGroup';

  /** 
   * @source src/routes/shipper/(my-contact)/-components/UploadContactExcell.amdl.tsx
   * @see {@link file:///home/edi/Documents/workbeanch/new_work/raaz/src/routes/shipper/(my-contact)/-components/UploadContactExcell.amdl.tsx}
   */
export type UploadContactExcell = 'UploadContactExcell';

  /** 
   * @source src/routes/shipper/(search-truck)/-components/FilterSortModal.mdl.tsx
   * @see {@link file:///home/edi/Documents/workbeanch/new_work/raaz/src/routes/shipper/(search-truck)/-components/FilterSortModal.mdl.tsx}
   */
export type FilterSortModal = 'FilterSortModal';

  /** 
   * @source src/routes/shipper/(shipper)/-components/AcceptedBIdMessage.mdl.tsx
   * @see {@link file:///home/edi/Documents/workbeanch/new_work/raaz/src/routes/shipper/(shipper)/-components/AcceptedBIdMessage.mdl.tsx}
   */
export type AcceptedBIdMessage = 'AcceptedBIdMessage';

  /** 
   * @source src/routes/shipper/(shipper)/-components/CounterBidOffer.amdl.tsx
   * @see {@link file:///home/edi/Documents/workbeanch/new_work/raaz/src/routes/shipper/(shipper)/-components/CounterBidOffer.amdl.tsx}
   */
export type CounterBidOffer = 'CounterBidOffer';

  /** 
   * @source src/routes/shipper/(shipper)/-components/ExtendPickupDate.amdl.tsx
   * @see {@link file:///home/edi/Documents/workbeanch/new_work/raaz/src/routes/shipper/(shipper)/-components/ExtendPickupDate.amdl.tsx}
   */
export type ExtendPickupDate = 'ExtendPickupDate';

  /** 
   * @source src/routes/shipper/(shipper)/-components/RejectBid.amdl.tsx
   * @see {@link file:///home/edi/Documents/workbeanch/new_work/raaz/src/routes/shipper/(shipper)/-components/RejectBid.amdl.tsx}
   */
export type RejectBid = 'RejectBid';

  /** 
   * @source src/routes/shipper/-components/ShipmentFilter.amdl.tsx
   * @see {@link file:///home/edi/Documents/workbeanch/new_work/raaz/src/routes/shipper/-components/ShipmentFilter.amdl.tsx}
   */
export type ShipmentFilter = 'ShipmentFilter';

  /** 
   * @source src/routes-shared/my-modals/BookableLoadsModal.amdl.tsx
   * @see {@link file:///home/edi/Documents/workbeanch/new_work/raaz/src/routes-shared/my-modals/BookableLoadsModal.amdl.tsx}
   */
export type BookableLoadsModal = 'BookableLoadsModal';

  /** 
   * @source src/routes-shared/my-modals/CarrierModal.amdl.tsx
   * @see {@link file:///home/edi/Documents/workbeanch/new_work/raaz/src/routes-shared/my-modals/CarrierModal.amdl.tsx}
   */
export type CarrierModal = 'CarrierModal';

  /** 
   * @source src/routes-shared/my-modals/CompanyFilterModal.amdl.tsx
   * @see {@link file:///home/edi/Documents/workbeanch/new_work/raaz/src/routes-shared/my-modals/CompanyFilterModal.amdl.tsx}
   */
export type CompanyFilterModal = 'CompanyFilterModal';

  /** 
   * @source src/routes-shared/my-modals/LoadRequirementsModal.amdl.tsx
   * @see {@link file:///home/edi/Documents/workbeanch/new_work/raaz/src/routes-shared/my-modals/LoadRequirementsModal.amdl.tsx}
   */
export type LoadRequirementsModal = 'LoadRequirementsModal';

  /** 
   * @source src/routes-shared/my-modals/PrivateLoadsModal.amdl.tsx
   * @see {@link file:///home/edi/Documents/workbeanch/new_work/raaz/src/routes-shared/my-modals/PrivateLoadsModal.amdl.tsx}
   */
export type PrivateLoadsModal = 'PrivateLoadsModal';

  /** 
   * @source src/routes-shared/my-modals/SearchBackModal.amdl.tsx
   * @see {@link file:///home/edi/Documents/workbeanch/new_work/raaz/src/routes-shared/my-modals/SearchBackModal.amdl.tsx}
   */
export type SearchBackModal = 'SearchBackModal';

  /** 
   * @source src/routes-shared/my-modals/TruckDetailModal.amdl.tsx
   * @see {@link file:///home/edi/Documents/workbeanch/new_work/raaz/src/routes-shared/my-modals/TruckDetailModal.amdl.tsx}
   */
export type TruckDetailModal = 'TruckDetailModal';

/**
 * Constant object for all modal names.
 * Use this for better "Go to Definition" support: openModal(MODALS.ConfirmationModal)
 */
export const MODALS = {
  /** 
   * @source src/components/RegsiterForPushNotification.mdl.tsx
   * @see {@link file:///home/edi/Documents/workbeanch/new_work/raaz/src/components/RegsiterForPushNotification.mdl.tsx}
   */
  RegsiterForPushNotification: 'RegsiterForPushNotification' as RegsiterForPushNotification,
  /** 
   * @source src/modals/ConfirmationModal.mdl.tsx
   * @see {@link file:///home/edi/Documents/workbeanch/new_work/raaz/src/modals/ConfirmationModal.mdl.tsx}
   */
  ConfirmationModal: 'ConfirmationModal' as ConfirmationModal,
  /** 
   * @source src/modals/SelectTruckModal.mdl.tsx
   * @see {@link file:///home/edi/Documents/workbeanch/new_work/raaz/src/modals/SelectTruckModal.mdl.tsx}
   */
  SelectTruckModal: 'SelectTruckModal' as SelectTruckModal,
  /** 
   * @source src/modals/SortByModal.mdl.tsx
   * @see {@link file:///home/edi/Documents/workbeanch/new_work/raaz/src/modals/SortByModal.mdl.tsx}
   */
  SortByModal: 'SortByModal' as SortByModal,
  /** 
   * @source src/modals/Test.mdl.tsx
   * @see {@link file:///home/edi/Documents/workbeanch/new_work/raaz/src/modals/Test.mdl.tsx}
   */
  Test: 'Test' as Test,
  /** 
   * @source src/modals/VehicleRegistrationModal.mdl.tsx
   * @see {@link file:///home/edi/Documents/workbeanch/new_work/raaz/src/modals/VehicleRegistrationModal.mdl.tsx}
   */
  VehicleRegistrationModal: 'VehicleRegistrationModal' as VehicleRegistrationModal,
  /** 
   * @source src/routes/carrier/components/BidDetail.amdl.tsx
   * @see {@link file:///home/edi/Documents/workbeanch/new_work/raaz/src/routes/carrier/components/BidDetail.amdl.tsx}
   */
  BidDetail: 'BidDetail' as BidDetail,
  /** 
   * @source src/routes/carrier/components/PlaceBid.amdl.tsx
   * @see {@link file:///home/edi/Documents/workbeanch/new_work/raaz/src/routes/carrier/components/PlaceBid.amdl.tsx}
   */
  PlaceBid: 'PlaceBid' as PlaceBid,
  /** 
   * @source src/routes/shipper/(my-contact)/-components/AddCarrier.amdl.tsx
   * @see {@link file:///home/edi/Documents/workbeanch/new_work/raaz/src/routes/shipper/(my-contact)/-components/AddCarrier.amdl.tsx}
   */
  AddCarrier: 'AddCarrier' as AddCarrier,
  /** 
   * @source src/routes/shipper/(my-contact)/-components/AddGroup.amdl.tsx
   * @see {@link file:///home/edi/Documents/workbeanch/new_work/raaz/src/routes/shipper/(my-contact)/-components/AddGroup.amdl.tsx}
   */
  AddGroup: 'AddGroup' as AddGroup,
  /** 
   * @source src/routes/shipper/(my-contact)/-components/EditCarrier.amdl.tsx
   * @see {@link file:///home/edi/Documents/workbeanch/new_work/raaz/src/routes/shipper/(my-contact)/-components/EditCarrier.amdl.tsx}
   */
  EditCarrier: 'EditCarrier' as EditCarrier,
  /** 
   * @source src/routes/shipper/(my-contact)/-components/EditGroup.amdl.tsx
   * @see {@link file:///home/edi/Documents/workbeanch/new_work/raaz/src/routes/shipper/(my-contact)/-components/EditGroup.amdl.tsx}
   */
  EditGroup: 'EditGroup' as EditGroup,
  /** 
   * @source src/routes/shipper/(my-contact)/-components/UploadContactExcell.amdl.tsx
   * @see {@link file:///home/edi/Documents/workbeanch/new_work/raaz/src/routes/shipper/(my-contact)/-components/UploadContactExcell.amdl.tsx}
   */
  UploadContactExcell: 'UploadContactExcell' as UploadContactExcell,
  /** 
   * @source src/routes/shipper/(search-truck)/-components/FilterSortModal.mdl.tsx
   * @see {@link file:///home/edi/Documents/workbeanch/new_work/raaz/src/routes/shipper/(search-truck)/-components/FilterSortModal.mdl.tsx}
   */
  FilterSortModal: 'FilterSortModal' as FilterSortModal,
  /** 
   * @source src/routes/shipper/(shipper)/-components/AcceptedBIdMessage.mdl.tsx
   * @see {@link file:///home/edi/Documents/workbeanch/new_work/raaz/src/routes/shipper/(shipper)/-components/AcceptedBIdMessage.mdl.tsx}
   */
  AcceptedBIdMessage: 'AcceptedBIdMessage' as AcceptedBIdMessage,
  /** 
   * @source src/routes/shipper/(shipper)/-components/CounterBidOffer.amdl.tsx
   * @see {@link file:///home/edi/Documents/workbeanch/new_work/raaz/src/routes/shipper/(shipper)/-components/CounterBidOffer.amdl.tsx}
   */
  CounterBidOffer: 'CounterBidOffer' as CounterBidOffer,
  /** 
   * @source src/routes/shipper/(shipper)/-components/ExtendPickupDate.amdl.tsx
   * @see {@link file:///home/edi/Documents/workbeanch/new_work/raaz/src/routes/shipper/(shipper)/-components/ExtendPickupDate.amdl.tsx}
   */
  ExtendPickupDate: 'ExtendPickupDate' as ExtendPickupDate,
  /** 
   * @source src/routes/shipper/(shipper)/-components/RejectBid.amdl.tsx
   * @see {@link file:///home/edi/Documents/workbeanch/new_work/raaz/src/routes/shipper/(shipper)/-components/RejectBid.amdl.tsx}
   */
  RejectBid: 'RejectBid' as RejectBid,
  /** 
   * @source src/routes/shipper/-components/ShipmentFilter.amdl.tsx
   * @see {@link file:///home/edi/Documents/workbeanch/new_work/raaz/src/routes/shipper/-components/ShipmentFilter.amdl.tsx}
   */
  ShipmentFilter: 'ShipmentFilter' as ShipmentFilter,
  /** 
   * @source src/routes-shared/my-modals/BookableLoadsModal.amdl.tsx
   * @see {@link file:///home/edi/Documents/workbeanch/new_work/raaz/src/routes-shared/my-modals/BookableLoadsModal.amdl.tsx}
   */
  BookableLoadsModal: 'BookableLoadsModal' as BookableLoadsModal,
  /** 
   * @source src/routes-shared/my-modals/CarrierModal.amdl.tsx
   * @see {@link file:///home/edi/Documents/workbeanch/new_work/raaz/src/routes-shared/my-modals/CarrierModal.amdl.tsx}
   */
  CarrierModal: 'CarrierModal' as CarrierModal,
  /** 
   * @source src/routes-shared/my-modals/CompanyFilterModal.amdl.tsx
   * @see {@link file:///home/edi/Documents/workbeanch/new_work/raaz/src/routes-shared/my-modals/CompanyFilterModal.amdl.tsx}
   */
  CompanyFilterModal: 'CompanyFilterModal' as CompanyFilterModal,
  /** 
   * @source src/routes-shared/my-modals/LoadRequirementsModal.amdl.tsx
   * @see {@link file:///home/edi/Documents/workbeanch/new_work/raaz/src/routes-shared/my-modals/LoadRequirementsModal.amdl.tsx}
   */
  LoadRequirementsModal: 'LoadRequirementsModal' as LoadRequirementsModal,
  /** 
   * @source src/routes-shared/my-modals/PrivateLoadsModal.amdl.tsx
   * @see {@link file:///home/edi/Documents/workbeanch/new_work/raaz/src/routes-shared/my-modals/PrivateLoadsModal.amdl.tsx}
   */
  PrivateLoadsModal: 'PrivateLoadsModal' as PrivateLoadsModal,
  /** 
   * @source src/routes-shared/my-modals/SearchBackModal.amdl.tsx
   * @see {@link file:///home/edi/Documents/workbeanch/new_work/raaz/src/routes-shared/my-modals/SearchBackModal.amdl.tsx}
   */
  SearchBackModal: 'SearchBackModal' as SearchBackModal,
  /** 
   * @source src/routes-shared/my-modals/TruckDetailModal.amdl.tsx
   * @see {@link file:///home/edi/Documents/workbeanch/new_work/raaz/src/routes-shared/my-modals/TruckDetailModal.amdl.tsx}
   */
  TruckDetailModal: 'TruckDetailModal' as TruckDetailModal,
} as const;

export type FileNames = RegsiterForPushNotification | ConfirmationModal | SelectTruckModal | SortByModal | Test | VehicleRegistrationModal | BidDetail | PlaceBid | AddCarrier | AddGroup | EditCarrier | EditGroup | UploadContactExcell | FilterSortModal | AcceptedBIdMessage | CounterBidOffer | ExtendPickupDate | RejectBid | ShipmentFilter | BookableLoadsModal | CarrierModal | CompanyFilterModal | LoadRequirementsModal | PrivateLoadsModal | SearchBackModal | TruckDetailModal;
