// Auto-generated by vite-plugin-modal-types
import type { ReturnType as ReturnType_ConfirmationModal } from '../../modals/ConfirmationModal.mdl';
import type { ReturnType as ReturnType_Test } from '../../modals/Test.amdl';

export interface ModalRegistry {
  /** 
   * @source src/modals/ConfirmationModal.mdl.tsx
   * @see {@link file:///home/edi/Documents/workbeanch/new_work/raaz/src/modals/ConfirmationModal.mdl.tsx}
   */
  'ConfirmationModal': ReturnType_ConfirmationModal;
  /** 
   * @source src/modals/Test.amdl.tsx
   * @see {@link file:///home/edi/Documents/workbeanch/new_work/raaz/src/modals/Test.amdl.tsx}
   */
  'Test': ReturnType_Test;
}

  /** 
   * @source src/modals/ConfirmationModal.mdl.tsx
   * @see {@link file:///home/edi/Documents/workbeanch/new_work/raaz/src/modals/ConfirmationModal.mdl.tsx}
   */
export type ConfirmationModal = 'ConfirmationModal';

  /** 
   * @source src/modals/Test.amdl.tsx
   * @see {@link file:///home/edi/Documents/workbeanch/new_work/raaz/src/modals/Test.amdl.tsx}
   */
export type Test = 'Test';

/**
 * Constant object for all modal names.
 * Use this for better "Go to Definition" support: openModal(MODALS.ConfirmationModal)
 */
export const MODALS = {
  /** 
   * @source src/modals/ConfirmationModal.mdl.tsx
   * @see {@link file:///home/edi/Documents/workbeanch/new_work/raaz/src/modals/ConfirmationModal.mdl.tsx}
   */
  ConfirmationModal: 'ConfirmationModal' as ConfirmationModal,
  /** 
   * @source src/modals/Test.amdl.tsx
   * @see {@link file:///home/edi/Documents/workbeanch/new_work/raaz/src/modals/Test.amdl.tsx}
   */
  Test: 'Test' as Test,
} as const;

export type FileNames = ConfirmationModal | Test;
